import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, Check, FlaskConical, ShieldCheck, Users } from 'lucide-react';

const stages = [['Conócete',82],['Explora',68],['Prueba',51],['Compara',37],['Decide',29]];
const careers = [['Ingeniería de Sistemas',42],['Psicología',35],['Administración',31],['Arquitectura',24]];

export default function SchoolPanelPage() {
  return <div className="stack school-demo"><div className="page-title"><div><span className="eyebrow">DEMOSTRACIÓN INSTITUCIONAL</span><h1>Una vista agregada para acompañar.</h1><p>Ejemplo de cómo un colegio podría observar participación sin convertir resultados individuales en etiquetas.</p></div><span className="badge">Datos ficticios</span></div><div className="notice"><ShieldCheck size={18}/><span>Esta pantalla usa información inventada para la presentación del MVP. Una versión real requeriría consentimiento, roles de acceso y revisión legal para datos de menores.</span></div><div className="school-kpis"><article className="panel"><Users/><span>Estudiantes participantes</span><strong>120</strong><small>promoción de ejemplo</small></article><article className="panel"><Check/><span>Ruta completada</span><strong>29%</strong><small>35 estudiantes</small></article><article className="panel"><FlaskConical/><span>Experiencias realizadas</span><strong>186</strong><small>en cuatro casos</small></article></div><div className="school-grid"><section className="panel"><div className="between"><div><span className="eyebrow">AVANCE DE LA RUTA</span><h2>Participación por etapa</h2></div><BarChart3/></div><div className="school-bars">{stages.map(([name,value])=><div key={name}><span>{name}<b>{value}%</b></span><div className="progress-track"><i style={{width:value+'%'}}/></div></div>)}</div></section><section className="panel"><span className="eyebrow">INTERÉS AGREGADO</span><h2>Alternativas más exploradas</h2><p className="small muted">Cuenta visitas a fichas, no “recomendaciones” definitivas.</p><ol className="rank-list">{careers.map(([name,value],i)=><li key={name}><span>0{i+1}</span><b>{name}</b><small>{value} exploraciones</small></li>)}</ol></section></div><section className="next-banner"><div><h3>Primero validemos la experiencia del estudiante.</h3><p>Este panel ilustra la posibilidad B2B. El MVP funcional principal es la ruta individual.</p></div><Link className="btn" to="/registro">Probar la ruta <ArrowRight size={17}/></Link></section></div>;
}
