import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Compass, Search, FlaskConical, Columns3, FileText, ArrowRight, Check, RotateCcw, Sparkles } from 'lucide-react';
import { useJourney } from '../../context/JourneyContext';
import { routeProgress, recommendations } from '../../utils/journey';
const steps=[['Conócete','Un momento para descubrir tus intereses.','conocete',Compass],['Explora','Diez alternativas, nuevas posibilidades.','explora',Search],['Prueba','Vive una pequeña parte de la profesión.','prueba',FlaskConical],['Compara','Pon tus opciones una al lado de la otra.','compara',Columns3],['Decide','Traza tus próximos pasos.','decide',FileText]];
export default function DashboardPage(){
 const {state,dispatch}=useJourney(); const [reset,setReset]=useState(false);
 const done=[!!state.studentScores,state.explored.length>0,Object.keys(state.completedSimulations).length>0,state.comparisonReviewed,!!state.finalCertainty];
 const next=Math.max(0,done.findIndex(d=>!d)); const top=recommendations(state)[0];
 return <div className="stack"><div className="page-title"><div><span className="eyebrow">UN FUTURO CON MÁS POSIBILIDADES</span><h1>Hola, {state.profile?.name || 'explorador'} <span className="wave">✳</span></h1><p>No necesitas tener todas las respuestas. Empecemos por explorar.</p></div><span className="badge">{routeProgress(state)} de 5 etapas</span></div>
 <section className="journey-hero"><div><span className="eyebrow">TU SIGUIENTE PASO</span><h2>{done.every(Boolean)?'Tu ruta sigue abierta.':next===0?'Todo empieza por conocerte.':steps[next][0]+', con un poco más de claridad.'}</h2><p>{done.every(Boolean)?'Revisa lo que descubriste y continúa validando tus alternativas.':steps[next][1]}</p><Link className="btn" to={done.every(Boolean)?'/app/decide':'/app/'+steps[next][2]}>{done.every(Boolean)?'Ver mi ruta personal':next===0?'Comenzar cuestionario':'Continuar mi ruta'} <ArrowRight size={18}/></Link></div><div className="journey-compass"><Compass size={105} strokeWidth={1}/><span>LA DIRECCIÓN LA ELIGES TÚ</span></div></section>
 {state.initialCertainty===null&&<section className="panel certainty-panel"><div><h3>Antes de empezar, ¿qué tan clara tienes tu elección?</h3><p>No hay una respuesta correcta. Nos servirá para comparar cómo te sientes al terminar.</p></div><div><div className="rating-row">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>dispatch({type:'SET_INITIAL_CERTAINTY',payload:n})} aria-label={'Certeza inicial '+n+' de 5'}>{n}</button>)}</div><div className="scale-labels"><span>Nada clara</span><span>Muy clara</span></div></div></section>}
 <section><div className="section-heading compact"><h2>Tu ruta, paso a paso</h2><span className="muted small">Puedes volver a cualquier etapa</span></div><div className="dashboard-steps">{steps.map(([title,desc,path,Icon],i)=><Link className={'dashboard-step '+(done[i]?'done':i===next?'current':'')} key={path} to={'/app/'+path}><div className="step-number">{done[i]?<Check size={16}/>:'0'+(i+1)}</div><Icon size={23}/><h3>{title}</h3><p>{desc}</p><span>{done[i]?'Volver a explorar':i===next?'Empezar aquí':'Ver etapa'} <ArrowRight size={14}/></span></Link>)}</div></section>
 <div className="dashboard-bottom"><section className="panel"><span className="tile-icon violet"><Sparkles/></span><h3>{top?'Una alternativa para investigar':'La curiosidad es un buen comienzo.'}</h3><p>{top?top.name+' aparece entre tus alternativas. Revisa qué actividades implica y contrástala con otras opciones.':'Puedes empezar con una idea, varias carreras en mente o ninguna. Este espacio es para hacer preguntas, probar y aprender.'}</p><Link to={top?'/app/explora':'/app/prueba'} className="text-link">{top?'Revisar mis alternativas':'Conocer los retos'} <ArrowRight size={16}/></Link></section><section className="panel"><h3>Este es tu espacio.</h3><p>Tu avance se conserva en este navegador. En un dispositivo compartido, descarga tu reporte y borra tu ruta al terminar.</p><button className="text-link muted" onClick={()=>setReset(!reset)}><RotateCcw size={15}/> Reiniciar mi ruta</button>{reset&&<div className="reset-confirm" role="alert"><p>Se borrarán tu perfil y tus respuestas de este navegador. Esta acción no se puede deshacer.</p><button className="btn btn-danger" onClick={()=>{dispatch({type:'RESET_JOURNEY'});setReset(false);}}>Borrar mi avance</button><button className="btn btn-outline" onClick={()=>setReset(false)}>Cancelar</button></div>}</section></div></div>;
}
