import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, Compass } from 'lucide-react';
import { useJourney } from '../../context/JourneyContext';
import { questionsData } from '../../data/questions';
import { dimensions } from '../../utils/journey';
export default function AssessmentPage(){
 const {state,dispatch}=useJourney();
 const [index,setIndex]=useState(()=>Math.max(0,questionsData.findIndex(q=>!state.assessmentAnswers[q.id]))); const [completed,setCompleted]=useState(false);
 const q=questionsData[index], answers=state.assessmentAnswers, count=questionsData.filter(x=>answers[x.id]).length;
 if(completed)return <section className="completion panel narrow"><span className="tile-icon mint"><Check/></span><span className="eyebrow">PRIMER PASO COMPLETADO</span><h1>Ya tienes un punto de partida.</h1><p>Tus respuestas abren posibilidades. Ahora conoce las actividades detrás de cada alternativa.</p><Link className="btn" to="/app/explora">Explorar mis resultados <ArrowRight size={18}/></Link><button className="text-link" onClick={()=>setCompleted(false)}>Revisar mis respuestas</button></section>;
 return <div className="assessment-wrap"><div className="page-title"><div><span className="eyebrow">01 / CONÓCETE</span><h1>Empieza por lo que te mueve.</h1><p>Piensa en lo que disfrutas hoy. Puedes cambiar tus respuestas.</p></div></div><div className="assessment-progress"><span>Pregunta {index+1} de {questionsData.length}</span><span>{count} respuestas guardadas</span><div className="progress-track"><i style={{width:count/questionsData.length*100+'%'}}/></div></div><section className="panel question-panel"><span className="tile-icon sky"><Compass/></span><span className="eyebrow">{dimensions[q.dimension]}</span><h2>{q.text}</h2><fieldset><legend className="sr-only">¿Cuánto te identificas con esta frase?</legend><div className="answer-grid">{['Nada','Poco','Algo','Bastante','Mucho'].map((label,i)=><button key={label} type="button" aria-pressed={answers[q.id]===i+1} className={answers[q.id]===i+1?'selected':''} onClick={()=>dispatch({type:'DRAFT_ANSWER',payload:{[q.id]:i+1}})}><b>{i+1}</b><span>{label}</span></button>)}</div></fieldset><p className="small muted">No evaluamos tu capacidad. Exploramos tus preferencias.</p></section><div className="between"><button className="btn btn-outline" disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft size={17}/> Anterior</button>{index<questionsData.length-1?<button className="btn" disabled={!answers[q.id]} onClick={()=>setIndex(index+1)}>Siguiente <ArrowRight size={17}/></button>:<button className="btn" disabled={count!==questionsData.length} onClick={()=>{dispatch({type:'SAVE_ASSESSMENT_ANSWERS',payload:{answers}});setCompleted(true);}}>Ver mi perfil <ArrowRight size={17}/></button>}</div><p className="small muted text-center">Cuestionario exploratorio del MVP. No es un test psicológico validado.</p></div>;
}
