import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Compass, FlaskConical, Check, Sparkles, Route, Lightbulb, Columns3, Search, HeartHandshake } from 'lucide-react';
export default function LandingPage() {
 const steps=[['01','Conócete','Pon en palabras lo que disfrutas.',Compass],['02','Explora','Descubre alternativas y sus actividades.',Search],['03','Prueba','Vive una pequeña experiencia.',FlaskConical],['04','Compara','Contrasta lo que importa para ti.',Columns3],['05','Decide','Construye tus siguientes pasos.',Route]];
 return <>
 <section className="landing-hero page-width"><div className="hero-copy"><span className="eyebrow pill"><Sparkles size={15}/> TU FUTURO EMPIEZA CON CURIOSIDAD</span><h1>No tienes que<br/>adivinar tu futuro.<br/><em>Empieza a explorarlo.</em></h1><p>Antes de elegir una carrera, vive una parte de ella. Conoce tus intereses, prueba retos y descubre opciones que tengan sentido para ti.</p><div className="hero-actions"><Link className="btn" to="/registro">Comenzar mi ruta <ArrowRight size={18}/></Link><a className="btn btn-outline" href="#como-funciona">Conocer la experiencia <ArrowUpRight size={17}/></a></div><div className="hero-checks"><span><Check/> A tu ritmo</span><span><Check/> Sin respuestas correctas</span><span><Check/> Sin crear una cuenta</span></div></div>
 <div className="hero-art" aria-label="Ilustración de una ruta con alternativas de estudio"><span className="art-spark spark-one">✳</span><span className="art-spark spark-two">✦</span><div className="art-orbit"/><div className="art-card card-analysis"><span className="tile-icon sky"><Search/></span><small>DESCUBRE LO QUE TE MUEVE</small><strong>Tu curiosidad<br/>es el punto de partida.</strong><div className="mini-bars"><i/><i/><i/><i/><i/></div><span className="art-card-footer">Varias posibilidades <ArrowUpRight size={15}/></span></div><div className="art-card card-experience"><span className="tile-icon mint"><FlaskConical/></span><div><small>PRUEBA ALGO NUEVO</small><strong>¿Y si vivieras la carrera?</strong><span>Decisiones pequeñas. Nuevas perspectivas.</span></div></div><div className="art-note"><span><Check size={15}/></span>La decisión siempre es tuya.</div><div className="art-label">TU RUTA, NO UNA ETIQUETA <span>↗</span></div></div>
 </section>
 <div className="value-strip"><div className="page-width"><span>MENOS SUPOSICIONES.<br/><b>MÁS EXPERIENCIAS.</b></span><div><strong>10</strong> carreras para descubrir</div><div><strong>4</strong> retos para experimentar</div><div><strong>1</strong> ruta que construyes tú</div></div></div>
 <section id="como-funciona" className="page-width section-pad"><div className="section-heading"><div><span className="eyebrow">ASÍ FUNCIONA</span><h2>Un gran paso empieza<br/>con cinco pequeños.</h2></div><p>No necesitas tenerlo todo claro. Cada etapa te ayuda a formular mejores preguntas sobre tu futuro.</p></div><div className="steps-grid">{steps.map(([n,title,desc,Icon])=><div className="step-card" key={n}><div className="step-top"><Icon size={23}/><span>{n}</span></div><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
 <section className="page-width experience-section"><div className="experience-copy"><span className="eyebrow">APRENDE HACIENDO</span><h2>De “creo que me gusta”<br/>a “ya probé un poco”.</h2><p>Investiga una situación, toma una decisión y reflexiona sobre cómo te sentiste. Una primera aproximación al trabajo detrás de cada carrera.</p><Link className="text-link" to="/app/prueba">Explorar las experiencias <ArrowRight size={18}/></Link></div><div className="featured-experience"><span className="badge">INGENIERÍA INDUSTRIAL</span><FlaskConical className="feature-icon" size={40}/><h3>Haz que el proceso fluya.</h3><p>Un equipo. Tres etapas. Un cuello de botella.<br/>¿Por dónde empezarías?</p><div><span>8–12 min · Caso interactivo</span><Link to="/app/prueba/sim-ind" aria-label="Probar Ingeniería Industrial"><ArrowUpRight/></Link></div></div></section>
 <section className="page-width family-banner"><span className="tile-icon peach"><HeartHandshake/></span><div><h3>Acompañar también es parte de la ruta.</h3><p>Una conversación con tu familia u orientador puede abrir nuevas posibilidades.</p></div><Link to="/familias" className="btn btn-outline">Espacio para familias <ArrowUpRight size={17}/></Link></section>
 <section className="page-width faq-section"><div><span className="eyebrow">ANTES DE EMPEZAR</span><h2>Es normal tener preguntas.</h2><Lightbulb size={36}/></div><div>{[['¿VocaRuta elige mi carrera?','No. Te ayuda a explorar alternativas. El resultado es orientativo y la decisión sigue siendo tuya.'],['¿Qué significa mi porcentaje de afinidad?','Resume tus respuestas dentro de una matriz ilustrativa. No es una probabilidad de éxito ni un diagnóstico psicológico validado.'],['¿Qué pasa con mi avance?','Se guarda en este navegador. Puedes retomar después y descargar tu reporte. No necesitas correo ni contraseña.'],['¿Una simulación representa toda una profesión?','Es solo un primer acercamiento. Compleméntalo revisando planes de estudio, conversando con profesionales y con orientación humana.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 </>;
}
