export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/registro',
  ABOUT: '/acerca',
  FAMILIES: '/familias',
  SCHOOL: '/colegio',
  DASHBOARD: '/app',
  ASSESSMENT: '/app/conocete',
  EXPLORE: '/app/explora',
  SIMULATIONS: '/app/prueba',
  SIMULATION_DETAIL: '/app/prueba/:id',
  COMPARE: '/app/compara',
  REPORT: '/app/decide',
};
