import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Compass, ArrowRight } from 'lucide-react';
import { useJourney } from '../../context/JourneyContext';
export default function RegisterPage(){
 const {state,dispatch}=useJourney(); const navigate=useNavigate(); const [name,setName]=useState(state.profile?.name || ''); const [grade,setGrade]=useState(state.profile?.grade || ''); const [error,setError]=useState('');
 function submit(e){e.preventDefault();if(!name.trim()){setError('Escribe el nombre con el que quieres que te llamemos.');return;}dispatch({type:'PROFILE',payload:{name:name.trim(),grade}});navigate('/app');}
 return <section className="onboarding page-width"><div className="onboarding-intro"><span className="eyebrow">EMPECEMOS POR TI</span><h1>Tu próxima etapa<br/>merece una buena<br/><em>primera pregunta.</em></h1><p>No necesitas saber qué estudiar.<br/>Solo traer un poco de curiosidad.</p><div className="onboarding-symbol"><Compass size={100}/></div></div><form className="panel onboarding-form" onSubmit={submit}><span className="badge">TU ESPACIO PERSONAL</span><h2>Hola, futuro explorador.</h2><p>Personaliza tu ruta. No crearemos una cuenta ni te pediremos una contraseña.</p><label htmlFor="name">¿Cómo te llamamos?</label><input id="name" autoComplete="given-name" maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre o un apodo" required/><label htmlFor="grade">¿En qué etapa estás?</label><select id="grade" required value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Selecciona una opción</option><option>4.º de secundaria</option><option>5.º de secundaria</option><option>Explorando otras opciones</option></select>{error&&<p role="alert">{error}</p>}<p className="small muted">Tu perfil y tus respuestas se guardan solo en este navegador. Puedes borrarlos desde Mi ruta.</p><button className="btn" type="submit">Comenzar mi ruta <ArrowRight size={18}/></button><Link className="text-link" to="/app">Prefiero explorar sin nombre</Link><Link className="small muted" to="/acerca">Conocer el alcance y la privacidad del MVP</Link></form></section>;
}
