import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, Lightbulb } from 'lucide-react';
import { useJourney } from '../../context/JourneyContext';
import { simulationsData } from '../../data/simulations';
const feedbackQuestions=[['enjoy','¿Disfrutaste resolver la actividad?'],['learn','¿Te gustaría aprender más sobre este tema?'],['interest','¿Te interesó este tipo de problema?'],['future','¿Te gustaría explorar actividades similares?']];
export default function SimulationDetailPage(){
 const {id}=useParams();const {state,dispatch}=useJourney();const sim=simulationsData.find(s=>s.id===id);
 const [draft,setDraft]=useState(state.simulationDrafts[id]||{step:0,choice:'',reason:'',ratings:{}});const [saved,setSaved]=useState(false);
 function update(patch){const next={...draft,...patch};setDraft(next);dispatch({type:'SIM_DRAFT',payload:{id,draft:next}});}
 if(!sim)return <div className="panel empty-state"><h1>Esta experiencia no existe.</h1><Link className="btn" to="/app/prueba">Ver experiencias</Link></div>;
 const option=sim.options.find(o=>o.id===draft.choice);
 function finish(){if(!option||feedbackQuestions.some(([key])=>!draft.ratings[key]))return;dispatch({type:'COMPLETE_SIMULATION',payload:{simId:id,feedback:{ratings:draft.ratings,choice:draft.choice,reason:draft.reason,completedAt:new Date().toISOString()}}});dispatch({type:'SIM_DRAFT',payload:{id,draft:{step:0,choice:'',reason:'',ratings:{}}}});setSaved(true);}
 if(saved)return <section className="panel narrow completion"><span className="tile-icon mint"><Check/></span><span className="eyebrow">EXPERIENCIA GUARDADA</span><h1>Una nueva pista sobre ti.</h1><p>{Object.values(draft.ratings).reduce((a,b)=>a+b,0)>=14?'Parece que esta experiencia despertó tu curiosidad. Anota qué te gustaría seguir investigando.':'Descubrir lo que no te entusiasma también te ayuda a elegir. Prueba otra actividad y compara cómo te sientes.'}</p><div className="notice">{sim.takeaway}</div><p className="small muted">Guardamos tu elección, tu argumento y tu reflexión. La afinidad usa tu experiencia sin acumular puntos por repetir el reto.</p><div className="hero-actions"><Link className="btn" to="/app/compara">Comparar alternativas <ArrowRight size={17}/></Link><Link className="btn btn-outline" to="/app/prueba">Probar otra experiencia</Link></div></section>;
 return <div className="simulation-detail stack"><Link className="text-link muted" to="/app/prueba"><ArrowLeft size={16}/> Volver a experiencias · tu avance se guarda</Link><div><span className="eyebrow">APRENDE HACIENDO</span><h1>{sim.title}</h1></div><div className="simulation-stepper">{['El contexto','Tu decisión','Lo que descubres','Tu reflexión'].map((label,i)=><span className={draft.step===i?'active':draft.step>i?'done':''} key={label}><b>{draft.step>i?<Check size={14}/>:i+1}</b>{label}</span>)}</div><section className="panel simulation-stage">
 {draft.step===0&&<><span className="badge">CASO FICTICIO · {sim.duration}</span><h2>Hoy te toca explorar.</h2><p className="lead">{sim.context}</p><h3>Las pistas que tienes</h3><ul className="evidence-list">{sim.data.map((d,i)=><li key={d}><span>0{i+1}</span>{d}</li>)}</ul></>}
 {draft.step===1&&<><span className="eyebrow">TOMA UNA DECISIÓN</span><h2>{sim.question}</h2><div className="decision-options">{sim.options.map(o=><button key={o.id} aria-pressed={draft.choice===o.id} className={draft.choice===o.id?'selected':''} onClick={()=>update({choice:o.id})}><span>{o.id.toUpperCase()}</span>{o.text}{draft.choice===o.id&&<Check size={18}/>}</button>)}</div><label htmlFor="reason">¿Qué te llevó a elegirla? <span className="muted">(opcional)</span></label><textarea id="reason" maxLength={1500} value={draft.reason} onChange={e=>update({reason:e.target.value})} placeholder="Pienso que esta opción..."/><span className="small muted">{draft.reason.length}/1500 caracteres · Se guarda en tu reporte</span></>}
 {draft.step===2&&<><span className="tile-icon mint"><Lightbulb/></span><h2>Mira tu decisión desde otro ángulo.</h2><div className="notice"><b>Elegiste:</b> {option?.text}</div><p className="lead">{option?.feedback}</p><h3>¿Qué tiene que ver con la carrera?</h3><p>{sim.takeaway}</p><p className="small muted">Retroalimentación educativa del caso. No es una evaluación profesional de tus habilidades.</p></>}
 {draft.step===3&&<><span className="eyebrow">AHORA, ESCÚCHATE A TI</span><h2>¿Cómo fue la experiencia?</h2><p>1 = nada · 5 = mucho. Tu reflexión ayuda a ajustar la afinidad, incluso si no te gustó.</p><div className="reflection-questions">{feedbackQuestions.map(([key,text])=><fieldset key={key}><legend>{text}</legend><div className="rating-row">{[1,2,3,4,5].map(n=><button key={n} aria-label={text+' '+n+' de 5'} aria-pressed={draft.ratings[key]===n} className={draft.ratings[key]===n?'selected':''} onClick={()=>update({ratings:{...draft.ratings,[key]:n}})}>{n}</button>)}</div></fieldset>)}</div></>}
 <div className="between stage-controls"><button className="btn btn-outline" disabled={draft.step===0} onClick={()=>update({step:draft.step-1})}><ArrowLeft size={16}/> Anterior</button>{draft.step<3?<button className="btn" disabled={draft.step===1&&!draft.choice} onClick={()=>update({step:draft.step+1})}>Continuar <ArrowRight size={17}/></button>:<button className="btn" disabled={feedbackQuestions.some(([key])=>!draft.ratings[key])} onClick={finish}>Guardar experiencia <Check size={17}/></button>}</div></section></div>;
}
