import { Link, useSearchParams } from 'react-router-dom';
import { Clock, ArrowUpRight, FlaskConical, Check, ArrowRight } from 'lucide-react';
import { simulationsData } from '../../data/simulations';
import { careersData } from '../../data/careers';
import { useJourney } from '../../context/JourneyContext';
export default function SimulationsPage(){
 const {state}=useJourney();const [params]=useSearchParams();const career=params.get('career');const selected=careersData.find(c=>c.id===career);
 const list=[...simulationsData].sort((a,b)=>Number(b.careerId===career)-Number(a.careerId===career));
 return <div className="stack"><div className="page-title"><div><span className="eyebrow">03 / PRUEBA</span><h1>¿Y si lo pruebas primero?</h1><p>Pequeños retos para descubrir cómo te sientes haciendo, no solo imaginando.</p></div><span className="badge">{Object.keys(state.completedSimulations).length} de 4 experiencias</span></div><div className="notice">Casos educativos ficticios. Una experiencia breve no representa toda una profesión.</div>{selected&&!list.some(s=>s.careerId===career)&&<div className="panel"><h3>{selected.name}: continúa explorando</h3><p>Aún no hay una experiencia de esta carrera en el MVP. Puedes probar las cuatro disponibles y conversar con un profesional del área.</p><Link className="text-link" to="/app/explora">Volver al catálogo</Link></div>}<div className="simulation-grid">{list.map((s,i)=><article className={'simulation-card '+s.color+(s.careerId===career?' highlighted':'')} key={s.id}><div className="simulation-visual"><span className="eyebrow">EXPERIENCIA 0{i+1}</span><FlaskConical size={60} strokeWidth={1.3}/><span className="visual-mark">{['↗','✳','§','⌘'][i]}</span></div><div className="simulation-copy"><div className="between"><span className="eyebrow">{careersData.find(c=>c.id===s.careerId)?.name}</span>{state.completedSimulations[s.id]&&<span className="badge completed"><Check size={13}/> Completada</span>}</div><h2>{s.title}</h2><p>{s.subtitle}</p><div className="between"><span className="small muted"><Clock size={14}/> {s.duration}</span><Link className="btn btn-small" to={'/app/prueba/'+s.id}>{state.completedSimulations[s.id]?'Volver a probar':state.simulationDrafts[s.id]?'Continuar':'Probar experiencia'} <ArrowUpRight size={17}/></Link></div></div></article>)}</div>{Object.keys(state.completedSimulations).length>0&&<div className="next-banner"><div><h3>Ahora tienes algo más que una idea.</h3><p>Contrasta tus alternativas con lo que acabas de experimentar.</p></div><Link className="btn" to="/app/compara">Ir al comparador <ArrowRight size={17}/></Link></div>}</div>;
}
