import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, ArrowRight, Plus, Check, X, BookOpen } from 'lucide-react';
import { useJourney } from '../../context/JourneyContext';
import { recommendations, dimensions } from '../../utils/journey';
import { careersData } from '../../data/careers';
export default function ExplorePage(){
 const {state,dispatch}=useJourney(); const [query,setQuery]=useState(''); const [area,setArea]=useState('Todas'); const [detail,setDetail]=useState(null);
 const careers=state.studentScores?recommendations(state):careersData;
 const filtered=careers.filter(c=>(area==='Todas'||c.area===area)&&c.name.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(query.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'')));
 function open(c){setDetail(c);dispatch({type:'EXPLORE',payload:c.id});}
 return <div className="stack"><div className="page-title"><div><span className="eyebrow">02 / EXPLORA</span><h1>Hay más de un camino para ti.</h1><p>Conoce las actividades, encuentra conexiones y guarda hasta tres alternativas.</p></div><Link className="btn btn-outline" to="/app/compara">Comparar ({state.compareList.length}/3) <ArrowRight size={16}/></Link></div>
 {!state.studentScores?<div className="notice">Estás explorando el catálogo. <Link to="/app/conocete">Completa Conócete para ver tu afinidad personal →</Link></div>:<div className="profile-overview"><div><span className="eyebrow">TU PERFIL DE INTERESES</span><h3>Un punto de partida,<br/>no una etiqueta.</h3><Link className="text-link small" to="/app/conocete">Revisar respuestas</Link></div><div className="profile-bars">{Object.entries(dimensions).map(([key,label])=><div key={key}><span>{label}<b>{state.studentScores[key]} / 5</b></span><div className="progress-track"><i style={{width:state.studentScores[key]/5*100+'%'}}/></div></div>)}</div></div>}
 <div className="filter-bar"><label className="search-input"><Search size={18}/><input aria-label="Buscar carrera" placeholder="Busca una carrera..." value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar por área" value={area} onChange={e=>setArea(e.target.value)}>{['Todas',...new Set(careersData.map(c=>c.area))].map(a=><option key={a}>{a}</option>)}</select><span className="small muted">{filtered.length} alternativas</span></div>
 <div className="career-grid">{filtered.map((c,i)=><article className="panel career-card" key={c.id}><div className="between"><span className={'career-symbol tone-'+(i%4)}><BookOpen size={22}/></span>{c.compatibility!==undefined&&<span className="affinity">{c.compatibility}% <small>afinidad orientativa</small></span>}</div><span className="eyebrow">{c.area}</span><h3>{c.name}</h3><p>{c.description}</p>{c.reason&&<p className="career-reason">{c.reason}</p>}<div className="career-actions"><button className="text-link" onClick={()=>open(c)}>Conocer carrera <ArrowRight size={16}/></button><button className={'icon-button '+(state.compareList.includes(c.id)?'selected':'')} aria-label={(state.compareList.includes(c.id)?'Quitar ':'Comparar ')+c.name} aria-pressed={state.compareList.includes(c.id)} disabled={!state.compareList.includes(c.id)&&state.compareList.length>=3} onClick={()=>dispatch({type:'TOGGLE_COMPARE',payload:c.id})}>{state.compareList.includes(c.id)?<Check size={18}/>:<Plus size={18}/>}</button></div></article>)}</div>
 {!filtered.length&&<div className="panel empty-state"><Search size={32}/><h3>No encontramos esa carrera.</h3><p>Prueba otro término o elimina el filtro.</p><button className="btn btn-outline" onClick={()=>{setQuery('');setArea('Todas');}}>Limpiar filtros</button></div>}
 <details className="method-note"><summary>¿Cómo calculamos la afinidad?</summary><p>Las respuestas de 1 a 5 se promedian en cinco áreas y se convierten a una escala de 0 a 100. Cada carrera tiene pesos ilustrativos de 1 a 5. La afinidad es el promedio ponderado. Si completas su simulación, combinamos 75% de ese resultado con 25% de tu reflexión. Una experiencia que no disfrutas también cuenta. No mide aptitud ni probabilidad de éxito. La metodología requiere validación profesional.</p></details>
 {state.compareList.length===3&&<p className="notice">Ya elegiste tres alternativas. Quita una para agregar otra, o continúa al comparador.</p>}
 {detail&&<div className="dialog-backdrop" onClick={e=>{if(e.target===e.currentTarget)setDetail(null);}}><section className="dialog panel" role="dialog" aria-modal="true" aria-labelledby="career-title" onKeyDown={e=>{if(e.key==='Escape')setDetail(null);}}><button className="dialog-close icon-button" onClick={()=>setDetail(null)} autoFocus aria-label="Cerrar detalle"><X/></button><span className="eyebrow">{detail.area}</span><h2 id="career-title">{detail.name}</h2><p>{detail.description}</p><h3>Un vistazo al día a día</h3><p>{detail.tasks}</p><h3>Lo que podrías estudiar</h3><div className="tags">{detail.mainCourses.map(c=><span key={c}>{c}</span>)}</div><h3>Espacios de trabajo</h3><p>{detail.work}</p><p className="small muted">{detail.duration}. Descripción general: revisa la malla y duración de cada institución.</p><div className="hero-actions"><Link className="btn" to={'/app/prueba?career='+detail.id}>Explorar experiencias <ArrowRight size={17}/></Link><button className="btn btn-outline" disabled={!state.compareList.includes(detail.id)&&state.compareList.length>=3} onClick={()=>dispatch({type:'TOGGLE_COMPARE',payload:detail.id})}>{state.compareList.includes(detail.id)?'Quitar del comparador':'Agregar al comparador'}</button></div><button className="text-link" onClick={()=>setDetail(null)}>Volver al catálogo</button></section></div>}
 </div>;
}
