import { Outlet, NavLink, Link, useLocation } from 'react-router-dom';
import { Compass, LayoutDashboard, Search, FlaskConical, Columns3, FileText, ArrowLeft, CircleHelp } from 'lucide-react';
import Brand from '../components/Brand';
import { useJourney } from '../context/JourneyContext';
import { routeProgress } from '../utils/journey';
const nav = [['/app','Mi ruta',LayoutDashboard],['/app/conocete','Conócete',Compass],['/app/explora','Explora',Search],['/app/prueba','Prueba',FlaskConical],['/app/compara','Compara',Columns3],['/app/decide','Decide',FileText]];
export default function StudentLayout() {
  const {state,storageError} = useJourney(); const location = useLocation();
  const active = nav.find(([p]) => p !== '/app' && location.pathname.startsWith(p)) || nav[0];
  const progress = routeProgress(state)*20;
  return <div className="workspace"><a className="skip-link" href="#contenido">Saltar al contenido</a><aside className="sidebar"><Brand/><div className="sidebar-label">TU PRÓXIMO CAPÍTULO</div><nav aria-label="Tu ruta vocacional">{nav.map(([path,label,Icon],i) => <NavLink key={path} to={path} end={path==='/app'} className={({isActive}) => isActive ? 'side-link active':'side-link'}><Icon size={19}/><span>{label}</span>{i>0 && <small>0{i}</small>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="route-progress"><span>Tu recorrido <b>{progress}%</b></span><div className="progress-track"><i style={{width:progress+'%'}}/></div><p>Paso a paso, a tu ritmo.</p></div><Link to="/acerca" className="side-link"><CircleHelp size={18}/> Cómo funciona el MVP</Link><Link to="/" className="side-link"><ArrowLeft size={18}/> Volver al inicio</Link></div></aside><div className="workspace-body"><header className="workspace-header"><span>Mi espacio <span className="breadcrumb">/ {active[1]}</span></span><div className="profile-chip"><span className="save-state">{storageError?'No se pudo guardar':'Guardado en este dispositivo'}</span><span className="avatar">{state.profile?.name?.charAt(0).toUpperCase() || 'V'}</span><span>{state.profile?.name || 'Explorador'}</span></div></header><main id="contenido" className="workspace-main" key={location.pathname}>{storageError && <p role="alert" className="notice">El navegador no permite guardar el avance. Descarga tu reporte antes de cerrar.</p>}<Outlet/></main><footer className="workspace-footer">VocaRuta · Tu futuro se explora, no se adivina.<span>MVP de orientación vocacional</span></footer></div></div>;
}
